devices:

  scope:

    SIGLENT_SDS2000:
      resource: TCPIP0::10.10.10.90::INSTR

    RUS_HMO3000:
      resource: TCPIP0::10.10.10.91::INSTR

    RIGOL_MSO1000:
      resource: TCPIP0::10.10.10.92::INSTR

  dmm:

    OWON_XDM1000:
      resource: AUTO

    RIGOL_DMM800:
      resource: TCPIP0::10.10.10.50::INSTR

  eload:

    EASTTESTER_ET54:
      resource: AUTO

    PEAKTECH_2275:
      resource: AUTO


selected:

  scope: SIGLENT_SDS2000
  dmm: OWON_XDM1000
  eload: EASTTESTER_ET54