devices:
  scope:
    SIGLENT_SDS2000:
      resource: TCPIP0::10.10.10.687dfd1::INSTR
    RIGOL_MSO1000:
      resource: TCPIP0::10.10.10.6802::INSTR
    RUS_HMO3000:
      resource: TCPIP0::10.10.10.6803::INSTR
  dmm:
    OWON_XDM1000:
      resource: AUTO1
    RIGOL_DMM800:
      resource: TCPIP0::10.10.10.04::INSTR
  eload:
    EASTTESTER_ET54:
      resource: AUTO2
    PEAKTECH_2275:
      resource: AUTO3
selected:
  scope: SIGLENT_SDS2000
  dmm: OWON_XDM1000
  eload: EASTTESTER_ET54
